import { Feather } from '@expo/vector-icons';
import { useEffect, useState } from 'react';
import { ActivityIndicator, Linking, Modal, Pressable, ScrollView, StyleSheet, Text, View } from 'react-native';
import { SafeAreaView } from 'react-native-safe-area-context';
import colors from '@/constants/colors';
import { api, type SignItem } from '@/lib/api';
import { useAccessibility } from '@/context/AccessibilityContext';

export default function LearnScreen() { const [categories, setCategories] = useState<Array<{ category: string; count: number }>>([]); const [category, setCategory] = useState<string>(); const [signs, setSigns] = useState<SignItem[]>([]); const [selected, setSelected] = useState<SignItem | null>(null); const { highContrast, textScale } = useAccessibility(); useEffect(() => { api.categories().then((data) => { setCategories(data); setCategory(data[0]?.category); }).catch(() => undefined); }, []); useEffect(() => { api.signs(category).then(setSigns).catch(() => setSigns([])); }, [category]); return <SafeAreaView style={[styles.screen, highContrast && styles.contrast]}><ScrollView contentContainerStyle={styles.content}><Text style={[styles.title, { fontSize: 25 * textScale }]}>Learn ISL</Text><ScrollView horizontal showsHorizontalScrollIndicator={false} contentContainerStyle={styles.chips}>{categories.map((item) => <Pressable key={item.category} onPress={() => setCategory(item.category)} style={[styles.chip, item.category === category && styles.activeChip]}><Text style={[styles.chipText, item.category === category && styles.activeText]}>{item.category} ({item.count})</Text></Pressable>)}</ScrollView>{signs.length === 0 ? <ActivityIndicator /> : <View style={styles.grid}>{signs.map((sign) => <Pressable key={sign.id} style={styles.card} onPress={() => setSelected(sign)}><View style={styles.preview}><Feather name="play" size={24} color={colors.light.primary} /></View><Text style={styles.word}>{sign.word}</Text><Text style={styles.description}>{sign.description}</Text></Pressable>)}</View>}</ScrollView><Modal visible={selected !== null} transparent animationType="fade" onRequestClose={() => setSelected(null)}><View style={styles.modalBackdrop}><View style={styles.modal}><Text style={styles.modalTitle}>{selected?.word}</Text><Text style={styles.description}>{selected?.description}</Text><Pressable style={styles.play} onPress={() => selected?.videoUrl && Linking.openURL(selected.videoUrl)}><Feather name="play" size={18} color="#FFF" /><Text style={styles.playText}>Play sign video</Text></Pressable><Pressable onPress={() => setSelected(null)}><Text style={styles.close}>Close</Text></Pressable></View></View></Modal></SafeAreaView>; }
const styles = StyleSheet.create({ screen: { backgroundColor: colors.light.background, flex: 1 }, contrast: { backgroundColor: '#000' }, content: { padding: 22 }, title: { color: colors.light.foreground, fontFamily: 'Inter_700Bold', marginBottom: 15 }, chips: { gap: 8, paddingBottom: 20 }, chip: { borderColor: colors.light.border, borderRadius: 18, borderWidth: 1, paddingHorizontal: 13, paddingVertical: 9 }, activeChip: { backgroundColor: colors.light.primary, borderColor: colors.light.primary }, chipText: { color: colors.light.mutedForeground, fontFamily: 'Inter_500Medium', fontSize: 12 }, activeText: { color: colors.light.primaryForeground }, grid: { flexDirection: 'row', flexWrap: 'wrap', gap: 12 }, card: { backgroundColor: colors.light.card, borderColor: colors.light.border, borderRadius: 14, borderWidth: 1, padding: 12, width: '47%' }, preview: { alignItems: 'center', aspectRatio: 1.3, backgroundColor: colors.light.accent, justifyContent: 'center' }, word: { color: colors.light.cardForeground, fontFamily: 'Inter_700Bold', marginTop: 10 }, description: { color: colors.light.mutedForeground, fontFamily: 'Inter_400Regular', marginTop: 5 }, modalBackdrop: { alignItems: 'center', backgroundColor: 'rgba(0,0,0,.5)', flex: 1, justifyContent: 'center', padding: 24 }, modal: { backgroundColor: '#FFFDF8', borderRadius: 18, padding: 24, width: '100%' }, modalTitle: { color: colors.light.foreground, fontFamily: 'Inter_700Bold', fontSize: 22, marginBottom: 8 }, play: { alignItems: 'center', backgroundColor: colors.light.primary, borderRadius: 12, flexDirection: 'row', gap: 8, justifyContent: 'center', marginVertical: 20, padding: 13 }, playText: { color: '#FFF', fontFamily: 'Inter_700Bold' }, close: { color: colors.light.primary, fontFamily: 'Inter_600SemiBold', textAlign: 'center' } });
