import { Feather } from '@expo/vector-icons';
import { useEffect, useState } from 'react';
import { ActivityIndicator, Linking, Pressable, ScrollView, StyleSheet, Text, View } from 'react-native';
import { SafeAreaView } from 'react-native-safe-area-context';
import colors from '@/constants/colors';
import { api, type SavedItem } from '@/lib/api';
import { useAccessibility } from '@/context/AccessibilityContext';

export default function SavedScreen() { const [items, setItems] = useState<SavedItem[]>([]); const [loading, setLoading] = useState(true); const { highContrast, textScale } = useAccessibility(); useEffect(() => { api.saved().finally(() => setLoading(false)).then(setItems).catch(() => undefined); }, []); return <SafeAreaView style={[styles.screen, highContrast && styles.contrast]}><ScrollView contentContainerStyle={styles.content}><Text style={[styles.title, { fontSize: 25 * textScale }]}>Saved translations</Text>{loading ? <ActivityIndicator /> : items.length === 0 ? <Text style={styles.muted}>Saved translations will appear here.</Text> : items.map((item) => { const translation = item.translation; return <View key={item.id} style={styles.card}><View style={styles.copy}><Text style={styles.message}>{translation?.input_text ?? 'Translation'}</Text><Text style={styles.sequence}>{Array.isArray(translation?.sign_sequence) ? translation.sign_sequence.join(' · ') : ''}</Text></View><View style={styles.actions}><Pressable accessibilityLabel="Play saved translation" onPress={() => item.videoUrl && Linking.openURL(item.videoUrl)}><Feather name="play-circle" size={26} color={colors.light.primary} /></Pressable><Pressable accessibilityLabel="Remove saved translation" onPress={() => api.unsave(item.id).then(() => setItems((current) => current.filter((saved) => saved.id !== item.id)))}><Feather name="star" size={23} color={colors.light.primary} /></Pressable></View></View>; })}</ScrollView></SafeAreaView>; }
const styles = StyleSheet.create({ screen: { backgroundColor: colors.light.background, flex: 1 }, contrast: { backgroundColor: '#000' }, content: { padding: 22 }, title: { color: colors.light.foreground, fontFamily: 'Inter_700Bold', marginBottom: 20 }, card: { alignItems: 'center', backgroundColor: colors.light.card, borderColor: colors.light.border, borderRadius: 14, borderWidth: 1, flexDirection: 'row', marginBottom: 10, padding: 16 }, copy: { flex: 1 }, message: { color: colors.light.cardForeground, fontFamily: 'Inter_700Bold' }, sequence: { color: colors.light.mutedForeground, fontFamily: 'Inter_400Regular', marginTop: 6 }, actions: { alignItems: 'center', flexDirection: 'row', gap: 16 }, muted: { color: colors.light.mutedForeground, fontFamily: 'Inter_400Regular' } });
